// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr8VlHwWDszs7CFbfNh9pkLy9NR01tizs',
    appId: '1:285608597055:web:ab02ab6343584f0e368a8a',
    messagingSenderId: '285608597055',
    projectId: 'bayshore-library',
    authDomain: 'bayshore-library.firebaseapp.com',
    storageBucket: 'bayshore-library.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtN8q0nl4U40iZEF2mFRA9k3_Oxe3OwI4',
    appId: '1:285608597055:android:03f87532f4e49a95368a8a',
    messagingSenderId: '285608597055',
    projectId: 'bayshore-library',
    storageBucket: 'bayshore-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA58BZ5kFXrXcPNAt-Jxc0NQC949lyIk3E',
    appId: '1:285608597055:ios:8bd24c9586f2f3fb368a8a',
    messagingSenderId: '285608597055',
    projectId: 'bayshore-library',
    storageBucket: 'bayshore-library.firebasestorage.app',
    iosBundleId: 'com.example.libraryFrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA58BZ5kFXrXcPNAt-Jxc0NQC949lyIk3E',
    appId: '1:285608597055:ios:8bd24c9586f2f3fb368a8a',
    messagingSenderId: '285608597055',
    projectId: 'bayshore-library',
    storageBucket: 'bayshore-library.firebasestorage.app',
    iosBundleId: 'com.example.libraryFrontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr8VlHwWDszs7CFbfNh9pkLy9NR01tizs',
    appId: '1:285608597055:web:222f32e058c4c61e368a8a',
    messagingSenderId: '285608597055',
    projectId: 'bayshore-library',
    authDomain: 'bayshore-library.firebaseapp.com',
    storageBucket: 'bayshore-library.firebasestorage.app',
  );
}
